BOUNCE_LINES = [
    "🏇 {actor} is riding {target} wild and free!",
    "💕 {actor} bounces up and down on {target}!",
    "🏇 {actor} takes control and rides {target} all night!",
    "💕 {actor} grinds down on {target} with every bounce.",
    "🏇 {actor} sets the pace from on top of {target}!",
    "💕 {actor} looks down at {target} while bouncing away~",
    "🏇 {actor} rides {target} like a pro!",
    "💕 {actor} makes sure {target} feels every inch deeply.",
    "🏇 {actor} leans forward, grinding into {target}!",
    "💕 {actor} is bouncing with incredible rhythm on {target}!",
    "🏇 {actor} takes {target} for a wild ride!",
    "💕 {actor} loves the view from up top on {target}.",
    "🏇 {actor} works their hips, driving {target} crazy!",
    "💕 {actor} bounces harder and harder on {target}!",
    "🏇 {actor} holds onto {target} for balance while riding fast!",
    "💕 {actor} sinks down deep onto {target}...",
    "🏇 {actor} is tireless on top of {target}!",
    "💕 {actor} makes {target} hold their hips!",
    "🏇 {actor} rides {target} into bliss!",
    "💕 {actor} bounces until {target} can't take it anymore!",
]
