CUDDLE_LINES = [
    "💕 {actor} cuddles up close to {target}!",
    "🥰 {actor} wraps their arms around {target} warmly.",
    "💕 {actor} snuggles into {target}'s side~",
    "🥰 {actor} gives {target} the coziest hug!",
    "💕 {actor} nuzzles against {target} affectionately.",
    "🥰 {actor} holds {target} close and doesn't let go.",
    "💕 {actor} curls up with {target} happily.",
    "🥰 {actor} pulls {target} into a soft embrace.",
    "💕 {actor} rests their head on {target}'s shoulder.",
    "🥰 {actor} squeezes {target} in a gentle cuddle!",
    "💕 {actor} shares warmth with {target}~",
    "🥰 {actor} gives {target} the fluffiest cuddles.",
    "💕 {actor} snuggles closer to {target}!",
    "🥰 {actor} hugs {target} like a teddy bear~",
    "💕 {actor} melts into {target}'s arms.",
    "🥰 {actor} wraps {target} in a blanket of love!",
    "💕 {actor} can't stop cuddling {target}!",
    "🥰 {actor} wants to stay in {target}'s arms forever~",
    "💕 {actor} and {target} share the coziest moment.",
    "🥰 {actor} gives {target} all the cuddles!",
]
