HUG_LINES = [
    "🤗 {actor} hugs {target} tightly!",
    "💕 {actor} wraps their arms around {target}!",
    "🤗 {actor} gives {target} a warm hug~",
    "💕 {actor} squeezes {target} lovingly.",
    "🤗 {actor} glomps {target}!",
    "💕 {actor} hugs {target} like there's no tomorrow!",
    "🤗 {actor} pulls {target} into a big hug.",
    "💕 {actor} embraces {target} warmly~",
    "🤗 {actor} won't let go of {target}!",
    "💕 {actor} gives {target} the biggest hug ever.",
    "🤗 {actor} tackle-hugs {target}!",
    "💕 {actor} hugs {target} so tight~",
    "🤗 {actor} snuggles into a hug with {target}.",
    "💕 {actor} gives {target} a comforting hug!",
    "🤗 {actor} can't resist hugging {target}~",
    "💕 {actor} shares a heartfelt hug with {target}.",
    "🤗 {actor} hugs {target} with all their love!",
    "💕 {actor} gives {target} infinite hugs~",
    "🤗 {actor} wraps {target} in a cozy hug.",
    "💕 {actor} hugs {target} forever and ever!",
]
