KISS_EMOTES = [
    "<a:kiss1:1456831316451528784>",
    "<a:kiss2:1456831639261810952>",
    "<:kiss3:1456831825438838785>",
    "<:kiss4:1456831982926430402>",
    "<a:kiss5:1456832237545980001>",
    "<a:kiss6:1456832530648137849>",
]

KISS_LINES = [
    "{actor} kisses {target} sweetly! {emote}",
    "{actor} plants a soft kiss on {target}~ {emote}",
    "{actor} steals a kiss from {target}! {emote}",
    "{actor} gives {target} a gentle peck. {emote}",
    "{actor} leans in and kisses {target}! {emote}",
    "{actor} surprises {target} with a kiss~ {emote}",
    "{actor} can't resist kissing {target}! {emote}",
    "{actor} kisses {target} on the cheek. {emote}",
    "{actor} shares a loving kiss with {target}! {emote}",
    "{actor} gives {target} butterfly kisses~ {emote}",
    "{actor} kisses {target} tenderly. {emote}",
    "{actor} presses their lips to {target}'s! {emote}",
    "{actor} gives {target} a smooch! {emote}",
    "{actor} kisses {target}'s forehead gently. {emote}",
    "{actor} and {target} share a sweet kiss~ {emote}",
    "{actor} blows a kiss to {target}! {emote}",
    "{actor} can't stop kissing {target}! {emote}",
    "{actor} peppers {target} with kisses~ {emote}",
    "{actor} gives {target} the sweetest kiss! {emote}",
    "{actor} melts into a kiss with {target}~ {emote}",
]
