KISS_LINES = [
    "💋 {actor} kisses {target} sweetly!",
    "😘 {actor} plants a soft kiss on {target}~",
    "💋 {actor} steals a kiss from {target}!",
    "😘 {actor} gives {target} a gentle peck.",
    "💋 {actor} leans in and kisses {target}!",
    "😘 {actor} surprises {target} with a kiss~",
    "💋 {actor} can't resist kissing {target}!",
    "😘 {actor} kisses {target} on the cheek.",
    "💋 {actor} shares a loving kiss with {target}!",
    "😘 {actor} gives {target} butterfly kisses~",
    "💋 {actor} kisses {target} tenderly.",
    "😘 {actor} presses their lips to {target}'s!",
    "💋 {actor} gives {target} a smooch!",
    "😘 {actor} kisses {target}'s forehead gently.",
    "💋 {actor} and {target} share a sweet kiss~",
    "😘 {actor} blows a kiss to {target}!",
    "💋 {actor} can't stop kissing {target}!",
    "😘 {actor} peppers {target} with kisses~",
    "💋 {actor} gives {target} the sweetest kiss!",
    "😘 {actor} melts into a kiss with {target}~",
]
