# DM notification second-line variants.
# Keep these short for mobile lock-screen notifications.

PLAP_NOTIFY_LINES = [
    "{actor} definitely meant that!",
    "That smack from {actor} wasn’t subtle~",
    "{actor} knew exactly what they were doing…",
    "You felt that squeeze from {actor}, right?",
    "That one from {actor} counts!",
    "{actor} wasn’t being shy with that grab~",
    "That touch lingered… {actor} let it.",
    "{actor} really committed to that.",
    "You’re not imagining it — that was {actor}.",
    "{actor} made that feel very deliberate.",
    "Comfortable after that hit, huh? {actor}~",
    "That wasn’t an accident — {actor} chose that.",
    "{actor} put intention behind that squeeze.",
    "Hard to ignore a grab like that from {actor}.",
    "That smack was bold of {actor}~",
    "You definitely noticed that touch.",
    "That grab had meaning — very {actor}.",
    "{actor} didn’t hold back there.",
    "That squeeze stayed with you… {actor} knew it would.",
    "That felt warm — classic {actor}.",
    "You’re still thinking about that, aren’t you?",
    "{actor} made that feel personal.",
    "That was calm but confident — very {actor}.",
    "No rush pulling away after that… {actor} noticed.",
    "That felt intentional, didn’t it? {actor}~",
    "{actor} really chose to take that moment.",
    "That definitely registered — nice one, {actor}.",
    "That wasn’t just playful — {actor} meant it.",
    "That landed exactly how {actor} wanted.",
    "Yeah… you felt that because of {actor}.",
]

SUCC_NOTIFY_LINES = [
    "{actor} was very comfortable with that kiss~",
    "That lean-in from {actor} definitely wasn’t rushed.",
    "{actor} knew exactly what they were doing.",
    "You felt that pull-in from {actor}, right?",
    "That one from {actor} counts!",
    "{actor} wasn’t subtle staying that close~",
    "That closeness lingered… {actor} let it.",
    "{actor} really leaned into that.",
    "You’re not imagining it — that was {actor}.",
    "{actor} made that feel intentional.",
    "That felt dangerously cozy.",
    "That wasn’t accidental — {actor} chose that.",
    "{actor} took their time drawing you in.",
    "Hard to ignore something like that from {actor}.",
    "That was bold of {actor}~",
    "You definitely noticed that closeness.",
    "That felt personal — {actor} knew.",
    "{actor} wasn’t shy about staying close.",
    "That moment stayed with you… {actor} planned that.",
    "That felt warm and deliberate.",
    "You’re still thinking about it, huh?",
    "{actor} made that feel meaningful.",
    "That was calm, confident, and close.",
    "No rush pulling away there… {actor} noticed.",
    "That felt intentional, didn’t it? {actor}~",
    "{actor} really chose to pull you in.",
    "That definitely registered — nice one, {actor}.",
    "That wasn’t just playful — {actor} meant it.",
    "That landed exactly how {actor} wanted.",
    "Yeah… you felt that from {actor}.",
]
