PAT_LINES = [
    "✋ {actor} pats {target}'s head gently!",
    "🥰 {actor} gives {target} the best headpats~",
    "✋ {actor} ruffles {target}'s hair lovingly.",
    "🥰 {actor} pats {target} softly.",
    "✋ {actor} can't resist patting {target}!",
    "🥰 {actor} headpats {target} with care~",
    "✋ {actor} gives {target} comfort pats.",
    "🥰 {actor} pats {target}'s head reassuringly!",
    "✋ {actor} rewards {target} with headpats~",
    "🥰 {actor} strokes {target}'s hair gently.",
    "✋ {actor} pats {target} on the head!",
    "🥰 {actor} gives {target} all the headpats~",
    "✋ {actor} pets {target} affectionately.",
    "🥰 {actor} can't stop patting {target}!",
    "✋ {actor} gives {target} soothing pats~",
    "🥰 {actor} pats {target} like a good friend!",
    "✋ {actor} headpats {target} happily.",
    "🥰 {actor} gives {target} gentle head rubs~",
    "✋ {actor} pats {target}'s fluffy head!",
    "🥰 {actor} showers {target} with pats~",
]
