PLAP_LINES_INTIMATE_NATURAL = [
    "😶 {actor} plaps {target} and stays close, letting the moment linger.",
    "💥 Without hesitation, {actor} plaps {target}, closing the distance.",
    "❤️‍🔥 {actor} plaps {target} with confidence, clearly aware of how close they are.",
    "⚡ After {actor} plaps {target}, neither of them moves right away.",
    "🍑 {actor} plaps {target} softly, but the intention is unmistakable.",
    "💢 {actor} plaps {target} and remains right there, unbothered by the tension.",
    "💥 The way {actor} plaps {target} makes the closeness feel deliberate.",
    "❤️‍🔥 {actor} plaps {target}, lingering just long enough to make it personal.",
    "⚡ Maintaining eye contact, {actor} plaps {target} without backing off.",
    "🍑 {actor} plaps {target}, the space between them suddenly very small.",
    "💢 After {actor} plaps {target}, the playful energy shifts into something heavier.",
    "💥 {actor} plaps {target} and doesn’t pretend the moment is still casual.",
    "❤️‍🔥 Calm and certain, {actor} plaps {target} and stays close.",
    "⚡ {actor} plaps {target}, both clearly aware of the tension now.",
    "🍑 The way {actor} plaps {target} leaves no room for misunderstanding.",
    "💢 {actor} plaps {target}, letting the silence do the talking.",
    "💥 With quiet confidence, {actor} plaps {target} and doesn’t pull away.",
    "❤️‍🔥 {actor} plaps {target}, fully owning how intimate it suddenly feels.",
    "⚡ {actor} plaps {target}, the closeness afterward very intentional.",
    "🍑 After {actor} plaps {target}, neither rushes to break the moment.",
    "💢 {actor} plaps {target} gently, staying close like they enjoy the warmth between them.",
    "💥 {actor} plaps {target} with a soft smile that definitely means more!",
    "❤️‍🔥 {actor} plaps {target} playfully, but lingers just long enough to feel intentional…",
    "⚡ {actor} plaps {target} with cozy confidence and a teasing glance~",
    "🍑 {actor} plaps {target} like it’s affectionate… and maybe a little flirty!",
    "💢 {actor} plaps {target} softly, clearly enjoying how close they already are.",
    "💥 {actor} plaps {target} with a gentle touch and a knowing smile!",
    "❤️‍🔥 {actor} plaps {target} like it’s warm, familiar, and just a bit daring~",
    "⚡ {actor} plaps {target} and stays close, letting the moment breathe…",
    "🍑 {actor} plaps {target} with relaxed confidence and subtle intent.",

    "💢 {actor} plaps {target} playfully, but the look they give says it’s not just a joke…",
    "💥 {actor} plaps {target} with affectionate ease and quiet tension~",
    "❤️‍🔥 {actor} plaps {target} softly, enjoying the closeness more than they admit!",
    "⚡ {actor} plaps {target} with a warm laugh and lingering eyes…",
    "🍑 {actor} plaps {target} like it’s cozy, comfortable, and a little bold!",
    "💢 {actor} plaps {target} gently, clearly liking how natural this feels~",
    "💥 {actor} plaps {target} with teasing affection and calm confidence.",
    "❤️‍🔥 {actor} plaps {target} like it’s familiar, but charged…",
    "⚡ {actor} plaps {target} with warmth that carries a quiet promise!",
    "🍑 {actor} plaps {target} and smiles like they’re enjoying the tension~",

    "💢 {actor} plaps {target} slowly, like they know exactly what they’re doing.",
    "💥 {actor} plaps {target} with a look that definitely isn’t innocent.",
    "❤️‍🔥 {actor} plaps {target} and smiles like they’ve been waiting for an excuse.",
    "⚡ {actor} plaps {target} with confidence that feels dangerously intentional.",
    "🍑 {actor} plaps {target} like flirting was always the point.",
    "💢 {actor} plaps {target} and lets the moment hang just a little too long…",
    "💥 {actor} plaps {target} with teasing confidence and zero shame!",
    "❤️‍🔥 {actor} plaps {target} like they’re fully aware of the tension.",
    "⚡ {actor} plaps {target} and enjoys the reaction way too much~",
    "🍑 {actor} plaps {target} like it’s half teasing, half promise…",

    "💢 {actor} plaps {target} with playful affection and warm energy.",
    "💥 {actor} plaps {target} like it’s an inside joke only they understand.",
    "❤️‍🔥 {actor} plaps {target} with soft confidence that feels safe.",
    "⚡ {actor} plaps {target} and laughs quietly afterward.",
    "🍑 {actor} plaps {target} like it’s easy, intimate, and intentional.",
    "💢 {actor} plaps {target} with a cozy smile and teasing eyes~",
    "💥 {actor} plaps {target} gently, clearly enjoying the closeness.",
    "❤️‍🔥 {actor} plaps {target} and doesn’t bother pretending it was accidental.",
    "⚡ {actor} plaps {target} with calm affection and subtle flirtation.",
    "🍑 {actor} plaps {target} like the closeness is the point."
]
