PLAP_LINES_INTIMATE_NATURAL = [
    # --- Impact / Sound ---
    "💥 {actor} slams into {target}, the impact echoing through the room!",
    "🍑 {actor} hits {target} from behind, leaving a stinging red handprint.",
    "💥 {actor} pounds {target} relentlessly, not giving them a second to breathe.",
    "🍑 {actor} grinds against {target}, causing a ripple of pleasure...",
    "💥 {actor} matches {target}’s rhythm, their bodies crashing together!",
    "🍑 {actor} makes {target} arch their back with every hit!",
    "💥 {actor} takes {target} with a feral energy, losing all restraint!",
    "🍑 {actor} creates so much friction inside {target} it’s maddening!",
    "💥 {actor} leaves {target} covered in sweat and shaking...",
    "🍑 {actor} hits {target} right in the spot, over and over~",
    "💥 {actor} speeds up, sensing {target} is close to the edge!",
    "🍑 {actor} claims {target} with a possessive, deep rhythm!",
    "💥 {actor} makes the bedframe creak loudly with {target}!",
    "🍑 {actor} flushes {target}’s skin with the heat of their body!",
    "💥 {actor} pulls {target}’s hair gently to expose their neck~",
    "🍑 {actor} fucks {target} until they can’t stand up anymore...",
    "💥 {actor} uses confident, heavy strokes to finish {target}.",
    "🍑 {actor} smiles as {target} tightens around them!",
    "💥 {actor} makes a loud wet sound with every thrust!",
    "🍑 {actor} is clapping {target} cheeks so loud the neighbors know!",
    "💥 {actor} rails {target} like a jackhammer!",
    "🍑 {actor} leaves their handprint on {target} ass permanently~",
    "💥 {actor} makes {target} scream their name!",
    "🍑 {actor} is destroying {target} in the best way possible...",
    "💥 {actor} has {target} shaking like a leaf!",
    "🍑 {actor} is hitting depths {target} didn't know they had!",
    "💥 {actor} is relentless, pure stamina!",
    "🍑 {actor} loves the sound of skin on skin with {target}~",
    "💥 {actor} is making {target} see god right now!",
    "🍑 {actor} is using {target} like a toy!",
    "💥 {actor} impacts {target} so hard they lose their breath!",
    "🍑 {actor} creates a symphony of wet claps with {target}!",
    "💥 {actor} is going beast mode on {target}!",
    "🍑 {actor} leaves {target} trembling with every hit!",
    "💥 {actor} is punishing {target} glutes!",
    "🍑 {actor} makes {target} squeak with the force of it!",
    "💥 {actor} sounds like applause, but better!",
    "🍑 {actor} generates heat you can feel from across the room!",
    "💥 {actor} is hammering away at {target} resistance!",
    "🍑 {actor} leaves no doubt who is in charge!",
    "💥 {actor} makes {target} grab the sheets for dear life!",
    "🍑 {actor} shakes the whole room with their rhythm!",
    "💥 {actor} is a force of nature inside {target}!",
    "🍑 {actor} creates a steady, loud beat with {target} body!",
    "💥 {actor} is relentless and mesmerizing!",
    "🍑 {actor} makes {target} body ripple with impact!",
    "💥 {actor} hits hard, fast, and deep!",
    "🍑 {actor} loves the sting of skin on skin!",
    "💥 {actor} makes sure {target} feels every single thrust!",
    "🍑 {actor} is audibly wrecking {target}!",

    # --- Deep / Filling ---
    "❤️‍🔥 {actor} fills {target} completely, stretching them out...",
    "⚡ {actor} thrusts into {target} with a rhythm that makes their toes curl~",
    "❤️‍🔥 {actor} enters {target} slow and heavy, feeling every inch~",
    "⚡ {actor} wrecks {target} with deep strokes, whispering dirt in their ear.",
    "❤️‍🔥 {actor} buries themselves in {target}, the heat overwhelming~",
    "❤️‍🔥 {actor} pins {target} against the wall, the impact shaking them.",
    "⚡ {actor} bites {target}’s lip while thrusting to stay quiet~",
    "❤️‍🔥 {actor} keeps a perfect, steady pace inside {target}.",
    "⚡ {actor} grips {target}’s waist firm to pull them deeper!",
    "❤️‍🔥 {actor} bottoms out inside {target}, filling them to the brim~",
    "❤️‍🔥 {actor} starts slow inside {target}, then ramps up the speed~",
    "⚡ {actor} traces {target}’s spine while thrusting deep.",
    "❤️‍🔥 {actor} owns {target} completely in this moment!",
    "⚡ {actor} breaks the tension by driving deep into {target}.",
    "❤️‍🔥 {actor} kisses {target}’s neck mid-thrust, muffling a moan.",
    "⚡ {actor} builds the pleasure in {target} with every hit!",
    "❤️‍🔥 {actor} holds {target} close for the aftershocks~",
    "⚡ {actor} makes {target} whimper softly with deep impact.",
    "❤️‍🔥 {actor} stretches {target} wide open!",
    "⚡ {actor} feels so good inside {target} they might pop!",
    "❤️‍🔥 {actor} is buried to the hilt in {target}...",
    "⚡ {actor} makes {target} feel full and complete~",
    "❤️‍🔥 {actor} is rearranging {target} guts!",
    "⚡ {actor} hits that deep spot that breaks {target} brain!",
    "❤️‍🔥 {actor} is taking up every inch of space inside {target}!",
    "⚡ {actor} belly swells slightly (metaphorically)~",
    "❤️‍🔥 {actor} stays deep inside {target}, just pulsing...",
    "⚡ {actor} makes {target} gasp for air with every thrust!",
    "❤️‍🔥 {actor} is mating with {target} for real!",
    "⚡ {actor} locks hips with {target} and grinds deep...",
    "❤️‍🔥 {actor} fits inside {target} like a puzzle piece.",
    "⚡ {actor} enters {target} soul through their body.",
    "❤️‍🔥 {actor} is incredibly thick inside {target}!",
    "⚡ {actor} pushes past {target} limits gently.",
    "❤️‍🔥 {actor} makes {target} feel full to bursting!",
    "⚡ {actor} connects deeply with {target} on every level.",
    "❤️‍🔥 {actor} loves the tightness of {target} around them.",
    "⚡ {actor} slides in and out like silk.",
    "❤️‍🔥 {actor} grounds {target} with their weight.",
    "⚡ {actor} makes {target} feel safe but ruined.",
    "❤️‍🔥 {actor} is addicted to the feeling of {target} insides.",
    "⚡ {actor} wants to stay inside {target} forever.",
    "❤️‍🔥 {actor} pulses deep within {target}...",
    "⚡ {actor} feels {target} hreatbeat from the inside.",
    "❤️‍🔥 {actor} is overwhelmingly present in {target}.",
    "⚡ {actor} leaves no empty space in {target}.",
    "❤️‍🔥 {actor} is heavy, hot, and perfect for {target}.",
    "⚡ {actor} makes {target} feel stretched and satisfied.",
    "❤️‍🔥 {actor} knows exactly how to fill the void.",
    "⚡ {actor} is deep enough to touch {target} heart.",

    # --- Dominant / Control ---
    "💢 {actor} holds {target} down and uses them, dominating the moment!",
    "💢 {actor} controls {target} with deep thrusts, knowing they like it!",
    "⚡ {actor} rubs against {target}’s sweet spot during the pauses.",
    "💢 {actor} fucks {target} so good that their eyes roll back...",
    "💢 {actor} demands {target} look back at them while they work.",
    "💢 {actor} makes a wet, heavy sound as they slide into {target}.",
    "⚡ {actor} leaves {target} trembling after a heavy session.",
    "💢 {actor} enjoys the view of {target} taking every inch...",
    "💢 {actor} delivers a satisfying *smack* against {target}.",
    "💢 {actor} collapses on top of {target}, exhausted and spent.",
    "💥 {actor} moves inside {target} with a hypnotic, rolling motion~",
    "🍑 {actor} leaves {target} messy and ruined...",
    "💢 {actor} ignores {target}’s weak protests and goes harder!",
    "💢 {actor} finishes deep inside {target}, filling them up...",
    "💢 {actor} makes {target} beg for it!",
    "⚡ {actor} holds {target} down so they can't escape!",
    "💢 {actor} is the boss of {target} right now!",
    "💢 {actor} tells {target} who they belong to!",
    "⚡ {actor} makes {target} say 'thank you'!",
    "💢 {actor} won't let {target} cum yet!",
    "💢 {actor} uses {target} until they are broken!",
    "⚡ {actor} is merciless with {target}!",
    "💢 {actor} breaks {target} mind with pleasure!",
    "💢 {actor} leaves {target} a drooping mess!",
    "⚡ {actor} owns {target} hole now!",
    "💢 {actor} marks {target} as their property!",
    "💢 {actor} makes {target} drool on the pillow!",
    "⚡ {actor} uses {target} thoroughly and completely!",
    "💢 {actor} ruins {target} for anyone else!",
    "💢 {actor} breeds {target} deep and hard!",
    "💢 {actor} holds {target} hair while pounding them.",
    "⚡ {actor} grins when {target} struggles.",
    "💢 {actor} loves seeing {target} give up control.",
    "💢 {actor} decides when {target} moves.",
    "⚡ {actor} is the only thing {target} can feel right now.",
    "💢 {actor} makes {target} desperate for more.",
    "💢 {actor} uses {target} for their own pleasure first.",
    "⚡ {actor} demands eye contact during the intense parts.",
    "💢 {actor} smiles at {target} undoing.",
    "💢 {actor} is a cruel but fair master.",
    "⚡ {actor} keeps going until {target} breaks.",
    "💢 {actor} loves a compliant {target}.",
    "💢 {actor} rewards {target} with deep strokes.",
    "⚡ {actor} punishes {target} with speed.",
    "💢 {actor} owns every moan {target} makes.",
    "💢 {actor} is absolute authority in the bedroom.",
    "⚡ {actor} makes {target} forget their own name.",
    "💢 {actor} leaves {target} totally spent.",
    "💢 {actor} is the king/queen of {target} body.",
    "⚡ {actor} commands {target} pleasure.",

    # --- Fast / Rough ---
    # "💥 {actor} goes rapid fire on {target}!",
    # "🍑 {actor} is blurry with speed!",
    # "💥 {actor} makes {target} shake with velocity!",
    # "🍑 {actor} doesn't stop for air!",
    # "💥 {actor} is a machine!",
    # "🍑 {actor} overwhelms {target} with sensation!",
    # "💥 {actor} is chasing the finish line!",
    # "🍑 {actor} creates too much friction to handle!",
    # "💥 {actor} makes {target} hold on for dear life!",
    # "🍑 {actor} is intense, fast, and perfect!",
    # "💥 {actor} drives {target} crazy with speed!",
    # "🍑 {actor} makes the world spin for {target}!",
    # "💥 {actor} is pure adrenaline!",
    # "🍑 {actor} leaves {target} breathless and dizzy!",
    # "💥 {actor} pounds away like it's the end of the world!",
    # "🍑 {actor} is unstoppable!",
    # "💥 {actor} finishes in record time (in a good way)!",
    # "🍑 {actor} creates a blur of pleasure!",
    # "💥 {actor} friction burns (the good kind)!",
    # "🍑 {actor} leaves {target} gasping!"
]
