POKE_LINES = [
    "👉 {actor} pokes {target}!",
    "😏 {actor} gives {target} a playful poke~",
    "👉 {actor} boops {target} on the cheek!",
    "😏 {actor} pokes {target}'s forehead.",
    "👉 {actor} can't stop poking {target}!",
    "😏 {actor} sneakily pokes {target}~",
    "👉 {actor} pokes {target} for attention!",
    "😏 {actor} gives {target} a boop.",
    "👉 {actor} pokes {target} repeatedly!",
    "😏 {actor} pokes {target}'s cheek~",
    "👉 {actor} gently pokes {target}.",
    "😏 {actor} pokes {target} with a grin!",
    "👉 {actor} boops {target}!",
    "😏 {actor} keeps poking {target}~",
    "👉 {actor} gives {target} the ultimate poke.",
    "😏 {actor} pokes {target} mischievously!",
    "👉 {actor} won't stop poking {target}~",
    "😏 {actor} pokes {target} softly.",
    "👉 {actor} pokes {target} just because!",
    "😏 {actor} surprises {target} with a poke~",
]
