SUCC_LINES_INTIMATE = [
    # --- Soft / Teasing ---
    "✨ {actor} works their tongue over {target}, teasing every sensitive spot~",
    "💖 {actor} tastes {target} slowly, savoring the flavor like a fine dessert.",
    "🍬 {actor} takes {target} into their mouth, humming with delight~",
    "🎀 {actor} teases the tip of {target} before taking them all the way in!",
    "✨ {actor} licks a stripe up {target}’s length, making them shiver~",
    "💖 {actor} treats {target} like a lollipop, swirling and sucking.",
    "🍬 {actor} kisses {target}’s inner thighs before diving back in~",
    "✨ {actor} looks up at {target} with big, doe eyes while working...",
    "💖 {actor} hums a vibration against {target} that feels electric~",
    "🍬 {actor} enjoys {target} so much they make happy little noises~",
    "💖 {actor} cradles {target} while using their mouth so gently...",
    "🍬 {actor} nuzzles {target} affectionately between licks.",
    "🎀 {actor} grazes their teeth lightly on {target} to tease...",
    "✨ {actor} pulls {target} closer, deepening the connection.",
    "🍬 {actor} tastes the pre-cum from {target} and smiles.",
    "😳 {actor} looks so innocent while doing such dirty things to {target}~",
    "✨ {actor} swirls their tongue around the head, just teasing~",
    "💖 {actor} gives {target} a break, only to dive right back down!",
    "🍬 {actor} holds {target}'s hand while going down on them...",
    "🎀 {actor} plays with {target}'s balls while working the shaft~",
    "✨ {actor} makes soft wet noises that drive {target} crazy...",
    "💖 {actor} loves the way {target} tastes today~",
    "🍬 {actor} is gentle but thorough, not missing a spot.",
    "🎀 {actor} keeps {target} on the edge, teasing the finish...",
    "✨ {actor} smiles against {target} skin, feeling them twitch.",
    "💖 {actor} is taking their sweet time, enjoying the view~",
    "🍬 {actor} makes {target} whimper with just their tongue.",
    "🎀 {actor} is being a good little pet for {target}...",
    "✨ {actor} worships {target} carefully and slowly.",
    "💖 {actor} loves making {target} feel good like this~",
    "✨ {actor} kisses the very tip, waiting for a reaction...",
    "💖 {actor} hums a little tune while working on {target}~",
    "🍬 {actor} looks up through their lashes, looking adorable.",
    "🎀 {actor} uses only the tip of their tongue for a minute.",
    "✨ {actor} breathes hot air onto {target} skin before licking.",
    "💖 {actor} is being so slow it's almost torture for {target}!",
    "🍬 {actor} laughs softly when {target} twitches.",
    "🎀 {actor} is exploring {target} like it's their first time.",
    "✨ {actor} holds eye contact until {target} blushes.",
    "💖 {actor} is treating {target} like royalty tonight.",
    "🍬 {actor} makes sure {target} is comfortable before starting.",
    "🎀 {actor} is gentle, sweet, and incredibly effective...",
    "✨ {actor} loves the sounds {target} makes.",
    "💖 {actor} could do this all day...",
    "🍬 {actor} is a perfectionist down there~",
    "🎀 {actor} is taking pride in their work.",
    "✨ {actor} feels {target} pulse against their lips.",
    "💖 {actor} kisses up the inner thigh, teasing...",
    "🍬 {actor} blows cool air on the wet spot~",
    "🎀 {actor} stops to smile at {target} before continuing.",

    # --- Enthusiastic / Service ---
    "💞 {actor} goes down on {target} with a hunger that can’t be satisfied!",
    "🍭 {actor} devours {target}, not leaving a single inch untouched.",
    "🌙 {actor} pleasures {target} with a deep, rhythmic motion...",
    "💫 {actor} lips wrap around {target} perfectly, creating a seal.",
    "😳 {actor} bobs their head on {target}, messy and enthusiastic!",
    "💞 {actor} services {target} with complete devotion, worshipping them...",
    "🍭 {actor} makes a mess of {target}, slobbering happily!",
    "🌙 {actor} uses their hand and mouth on {target} in perfect sync.",
    "💫 {actor} swirls their tongue around {target}, driving them crazy!",
    "💞 {actor} drains {target} completely, not stopping until they finish!",
    "🍭 {actor} plays with {target}, alternating between licks and suction.",
    "🌙 {actor} worships {target} on their knees, obedient and eager.",
    "🎀 {actor} keeps firm eye contact with {target} while going down.",
    "💫 {actor} shows off their oral skills on {target}, effortless and smooth!",
    "💞 {actor} takes absolute ownership of {target}’s pleasure.",
    "🍭 {actor} sucks {target} dry, determined to get every drop!",
    "🌙 {actor} slides up and down {target} with a slippery, wet sound~",
    "💫 {actor} focuses intense suction on the head of {target}!",
    "😳 {actor} makes {target} see stars with just their tongue~",
    "💖 {actor} wraps their lips tight around {target}, creating a vacuum!",
    "🍭 {actor} cleans {target} off thoroughly, leaving them shining.",
    "🌙 {actor} creates a rhythm on {target} that’s pure hypnotism~",
    "🎀 {actor} uses two hands to twist while they suck {target}!",
    "💞 {actor} slobs all over {target}, loving the mess!",
    "🍭 {actor} is drooling everywhere and doesn't even care~",
    "🌙 {actor} makes {target} their pacifier for the night.",
    "💫 {actor} is addicted to the taste of {target}!",
    "💞 {actor} wants to drink every drop {target} has.",
    "🍭 {actor} is working hard to make {target} explode!",
    "🌙 {actor} keeps going even when their jaw hurts...",
    "💞 {actor} is enthusiastic enough for two people!",
    "🍭 {actor} makes slurping noises that echo everywhere.",
    "🌙 {actor} is bobbing up and down so fast it's a blur!",
    "💫 {actor} uses a lot of spit to keep things slick.",
    "💞 {actor} has {target} grabbing the sheets in seconds.",
    "🍭 {actor} attacks {target} crotch with happy noises!",
    "🌙 {actor} is dedicated to making {target} see white.",
    "💫 {actor} treats {target} like an all-you-can-eat buffet.",
    "💞 {actor} is messy, loud, and incredible at this.",
    "🍭 {actor} leaves a trail of saliva everywhere~",
    "🌙 {actor} is working the shaft and the head at the same time!",
    "💫 {actor} uses suction that feels strong and amazing.",
    "💞 {actor} is determined to break {target} record time.",
    "🍭 {actor} loves the job and it shows.",
    "🌙 {actor} is practically vibrating with excitement.",
    "💫 {actor} barely comes up for air!",
    "💞 {actor} is a surprisingly talented throat goat.",
    "🍭 {actor} is making a puddle on the bed~",
    "🌙 {actor} grabs {target} hips to hold them steady.",
    "💫 {actor} swallows every twitch {target} makes.",

    # --- Intense / Deep Throat ---
    "🔥 {actor} swallows {target} whole, looking up with a dirty smirk.",
    "🎀 {actor} dominates {target} with their mouth, controlling the pace.",
    "🔥 {actor} deep throats {target}, taking it all without hesitation.",
    "😳 {actor} gags slightly on {target} but keeps going like a champ!",
    "🔥 {actor} attacks {target} with their mouth, hungry and wild.",
    "😳 {actor} drools all over {target}, making it nice and slick~",
    "✨ {actor} holds {target} still, refusing to let them buck hips!",
    "🔥 {actor} goes so deep on {target} their nose touches skin.",
    "💞 {actor} edges {target} with their mouth, stopping just before the end...",
    "💫 {actor} leaves {target} trembling and weak in the knees...",
    "🔥 {actor} creates a puddle beneath {target} with their enthusiasm.",
    "🔥 {actor} takes {target} down to the base, showing off!",
    "😳 {actor} tears up a little but takes every inch of {target}.",
    "🔥 {actor} loves the feeling of {target} hitting the back of their throat~",
    "🎀 {actor} forces {target} to stay still while they work.",
    "🔥 {actor} is relentless, not letting {target} breathe!",
    "😳 {actor} is choking on {target} and loving it~",
    "🔥 {actor} pushes {target} deeper, wanting more.",
    "🎀 {actor} uses {target} to scratch an itch in their throat.",
    "🔥 {actor} makes {target} feel huge inside them!",
    "😳 {actor} has messy face and glazed eyes from {target}...",
    "🔥 {actor} sucks {target} soul out through their dick!",
    "🎀 {actor} won't let {target} cum until they say so!",
    "🔥 {actor} is emptying {target} completely, no mercy.",
    "😳 {actor} takes it all and asks for seconds~",
    "🔥 {actor} makes {target} shake with how deep they go.",
    "🎀 {actor} knows exactly how to ruin {target} with their mouth.",
    "🔥 {actor} is a throat goat for {target}!",
    "😳 {actor} loves choking on {target}!",
    "🔥 {actor} makes {target} tap out!",
    "🔥 {actor} takes {target} so deep their eyes water.",
    "🎀 {actor} clamps down at the base, trapping {target}.",
    "🔥 {actor} uses {target} to face-fuck themselves essentially.",
    "😳 {actor} makes gutteral noises around {target}.",
    "🔥 {actor} lets {target} slide all the way down their throat.",
    "🎀 {actor} doesn't let {target} pull out for air.",
    "🔥 {actor} is testing their gag reflex today!",
    "😳 {actor} has saliva running down their chin from how deep it is.",
    "🔥 {actor} loves the feeling of being filled by {target}.",
    "🎀 {actor} is showing {target} exactly what that mouth can do.",
    "🔥 {actor} relaxes their throat to take even more.",
    "😳 {actor} is red-faced but refusing to stop.",
    "🔥 {actor} swallows hard around {target}.",
    "🎀 {actor} keeps taking it deeper and deeper.",
    "🔥 {actor} wants {target} to hit the bottom.",
    "😳 {actor} loves being used like this by {target}.",
    "🔥 {actor} is a glutton for {target}!",
    "🎀 {actor} makes {target} lose their mind with depth.",
    "🔥 {actor} is pushing their limits for {target}.",
    "😳 {actor} looks wrecked and beautiful.",

    # --- Messy / Sloppy ---
    "🍭 {actor} makes sure {target} is covered in spit.",
    "💞 {actor} loves making a mess on the sheets.",
    "🍭 {actor} lets a string of saliva connect them to {target}.",
    "💞 {actor} is noisy, wet, and passionate.",
    "🍭 {actor} doesn't care about looking pretty, just feeling good.",
    "💞 {actor} has spit all over their face and loves it.",
    "🍭 {actor} makes lewd slurping sounds on purpose.",
    "💞 {actor} cleans up {target} but gets messy doing it.",
    "🍭 {actor} is a slob for {target} cock.",
    "💞 {actor} loves the mix of spit and pre-cum.",
    "🍭 {actor} is getting sticky and messy for {target}.",
    "💞 {actor} leaves {target} absolutely drenched.",
    "🍭 {actor} makes wet popping noises with their mouth.",
    "💞 {actor} is covering {target} in love (and spit).",
    "🍭 {actor} is painting {target} with their tongue.",
    "💞 {actor} loves the sloppy sounds of oral.",
    "🍭 {actor} is making sure everyone knows what they're doing.",
    "💞 {actor} is uninhibited and messy.",
    "🍭 {actor} uses so much spit it drips down.",
    "💞 {actor} is a wonderful mess for {target}.",

    # --- Aftercare / Gentle Finish ---
    # "🌙 {actor} kisses the head gently after finishing.",
    # "🍬 {actor} cleans {target} up with soft licks.",
    # "🌙 {actor} cuddles into {target} crotch after.",
    # "🍬 {actor} rests their cheek on {target} thigh.",
    # "🌙 {actor} looks up and smiles, job well done.",
    # "🍬 {actor} hums happily, tasting {target}.",
    # "🌙 {actor} wipes their mouth and grins at {target}.",
    # "🍬 {actor} asks if {target} liked that~",
    # "🌙 {actor} loves the aftertaste of {target}.",
    # "🍬 {actor} wants a kiss after all that work.",
    # "🌙 {actor} snuggles close, happy to have served.",
    # "🍬 {actor} is glowing after pleasing {target}.",
    # "🌙 {actor} whispers sweet things against {target} skin.",
    # "🍬 {actor} gently licks up any mess made.",
    # "🌙 {actor} looks proud of themselves.",
    # "🍬 {actor} strokes {target} hair while resting.",
    # "🌙 {actor} is sleepy after such a good meal.",
    # "🍬 {actor} holds {target} knowing they did good.",
    # "🌙 {actor} loves the smell of {target} on them.",
    # "🍬 {actor} is the best at aftercare (oral edition)."
]
