SUCC_LINES_INTIMATE = [
    "😳 {actor} succs {target}, slow at first, like they’re testing the reaction.",
    "🔥 {actor} succs {target} with zero hesitation, like this was inevitable.",
    "🫣 {actor} succs {target} and doesn’t break the moment when it gets quiet.",
    "😈 {actor} succs {target}, making it painfully clear who’s in control.",
    "👁️ {actor} succs {target} and holds eye contact like it’s a challenge.",
    "🖤 {actor} succs {target} and stays close afterward, unapologetic.",
    "😶‍🌫️ {actor} succs {target}, and the vibe shifts into something heavier.",
    "🫶 {actor} succs {target} with a calm confidence that’s hard to ignore.",
    "🔥 {actor} succs {target}, lingering just long enough to make it personal.",
    "😳 After {actor} succs {target}, neither of them rushes to reset the mood.",
    "{actor} succs {target} gently, clearly enjoying the closeness.",
    "{actor} succs {target} with soft confidence and a warm smile!",
    "{actor} succs {target} like it’s cozy, intimate, and unhurried…",
    "{actor} succs {target} playfully, but stays close~",
    "{actor} succs {target} with relaxed affection and quiet intent.",
    "{actor} succs {target} like it feels natural to be right there…",
    "{actor} succs {target} with a teasing smile and calm ease!",
    "{actor} succs {target} softly, enjoying the shared warmth~",
    "{actor} succs {target} and lingers comfortably…",
    "{actor} succs {target} with affectionate confidence.",

    "{actor} succs {target} like it’s gentle, cozy flirting~",
    "{actor} succs {target} with subtle boldness!",
    "{actor} succs {target} and stays close without rushing…",
    "{actor} succs {target} like it’s intimate but relaxed.",
    "{actor} succs {target} with warm, teasing calm~",
    "{actor} succs {target} and smiles like they’re enjoying this!",
    "{actor} succs {target} softly, clearly comfortable…",
    "{actor} succs {target} with cozy affection and quiet tension~",
    "{actor} succs {target} like closeness is the point.",
    "{actor} succs {target} and lets the moment linger…",

    "{actor} succs {target} slowly, clearly enjoying the closeness.",
    "{actor} succs {target} with teasing confidence.",
    "{actor} succs {target} like they’re very comfortable right there.",
    "{actor} succs {target} and doesn’t rush a thing…",
    "{actor} succs {target} with deliberate, unhurried intent.",
    "{actor} succs {target} like the moment is exactly where they want to be.",
    "{actor} succs {target} and lets the tension build~",
    "{actor} succs {target} with soft confidence and clear desire.",
    "{actor} succs {target} and doesn’t pull away immediately…",
    "{actor} succs {target} like it’s quietly intense.",

    "{actor} succs {target} with warm, playful intent.",
    "{actor} succs {target} like it’s sweet, not rushed.",
    "{actor} succs {target} and seems completely at ease.",
    "{actor} succs {target} with gentle confidence.",
    "{actor} succs {target} like it’s cozy but charged~",
    "{actor} succs {target} with relaxed intimacy.",
    "{actor} succs {target} and enjoys the moment without hurry.",
    "{actor} succs {target} with quiet, confident affection.",
    "{actor} succs {target} like it feels right.",
    "{actor} succs {target} and stays comfortably close."
]
