TUCK_LINES = [
    "🛏️ {actor} tucks {target} into bed with a gentle smile.",
    "😴 {actor} wraps {target} up in a cozy blanket!",
    "🌙 {actor} gives {target} the warmest tuck in bed~",
    "🛏️ {actor} makes sure {target} is snug as a bug!",
    "😴 {actor} fluffs {target}'s pillow and tucks them in tight.",
    "🌙 {actor} whispers 'sweet dreams' as they tuck {target} in.",
    "🛏️ {actor} pulls the covers over {target} lovingly.",
    "😴 {actor} gently bundles {target} up for the night!",
    "🌙 {actor} ensures {target} is all cozy and tucked in~",
    "🛏️ {actor} gives {target} the coziest bedtime tuck!",
    "😴 {actor} tucks {target} in for a peaceful sleep.",
    "🌙 {actor} makes {target} a little blanket burrito!",
    "🛏️ {actor} smooths the blankets around {target} with care.",
    "😴 {actor} lovingly tucks in {target} for sweet dreams.",
    "🌙 {actor} gives {target} the perfect tuck in~",
    "🛏️ {actor} makes sure {target} won't be cold tonight!",
    "😴 {actor} gently tucks the blanket around {target}.",
    "🌙 {actor} prepares {target} for a comfy night's sleep!",
    "🛏️ {actor} tucks {target} in nice and cozy~",
    "😴 {actor} wishes {target} goodnight with a warm tuck in.",
]
